---
version: "3.7"
services:
  backend:
    build: ./backend
    container_name: backend
    ports: [8080:8080]
  postgres:
    image: postgres:11.6-alpine
    container_name: postgres
    ports: [5432:5432]
  frontend:
    build: ./frontend
    container_name: frontti
    ports: [3000:80]
